### ISSUE TITLE
explaining first few steps

### ISSUE THREAD

**Issue by thadikari** [wassname/viz_torch_optim#1]
Hi, thank you very much for this!

<img width="191" alt="untitled" src="https://user-images.githubusercontent.com/5517829/38629989-ab3059ca-3d83-11e8-8382-a2e03f4d458b.png">

With reference to attached image, It looks like a set of algorithms start off along the direction of RED arrow, and the rest along the direction of BLACK arrow. I would have expected all algorithms to start off in same direction, (the direction of the gradient at the start point, RED arrow in this case) but it doesn't seem to be the case. Do you have any idea why some of the algorithms start toward BLACK direction?

**Comment by thadikari** [comment]
Figured that out. The algorithms that follow RED only use the first moment only but BLACK algos use second moment as well and divide each gradient component by the second moment estimate. Got it. Sorry for trouble.

**Comment by wassname** [comment]
Oh interesting, I hadn't thought about it that deeply. Thanks for sharing the answer.
